### ISSUE TITLE
Other Overlays for Ultra96 + PYNQ

### ISSUE THREAD

**Issue by yasaspeiris** [Xilinx/PYNQ-ComputerVision#13]
I need to use the threshold overlay for my Ultra96 board. Can you please elaborate the steps I should follow in order to create the overlay?

**Comment by yasaspeiris** [comment]
If anyone can provide me the threshold overlay for ultra96 that would be a life saver. I do not have the SDSoC to built my own overlays.

**Comment by yasaspeiris** [comment]
If anyone can provide me the threshold overlay for ultra96 that would be a life saver. I do not have the SDSoC to build my own overlays.

**Comment by jackl-xilinx** [comment]
We've just uploaded an overlay for Ultra96 that includes filter2D, dilate, and threshold. Please give it a try. While this overlay does provide significant speedup for filter2D and dilate, the benefit of hardware acceleration for our configuration of threshold does not outweigh the cost of data movement for offloading and as a result, using the software threshold function is recommended for optimal performance. Please let us know if you have any further questions.
