### ISSUE TITLE
Error importing overlays

### ISSUE THREAD

**Issue by jamesthesken** [Xilinx/PYNQ-ComputerVision#19]
Board: Xilinx ZCU104
Firmware: PYNQ v2.4

After successfully cloning the repo I tried to run the first notebook. However was met with this error:
`---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-233859579777> in <module>()
      1 # Load filter2D + dilate overlay
      2 from pynq import Overlay
----> 3 bareHDMI = Overlay("/usr/local/lib/python3.6/dist-packages/"
      4                "pynq_cv/overlays/xv2Filter2DDilate.bit")
      5 import pynq_cv.overlays.xv2Filter2DDilate as xv2

/usr/local/lib/python3.6/dist-packages/pynq/overlay.py in __init__(self, bitfile_name, download, ignore_version)
    287 
    288         """
--> 289         super().__init__(bitfile_name, partial=False)
    290 
    291         hwh_path = get_hwh_name(self.bitfile_name)

/usr/local/lib/python3.6/dist-packages/pynq/pl.py in __init__(self, bitfile_name, partial)
   1812         else:
   1813             raise IOError('Bitstream file {} does not exist.'
-> 1814                           .format(bitfile_name))
   1815 
   1816         self.bit_data = dict()

OSError: Bitstream file /usr/local/lib/python3.6/dist-packages/pynq_cv/overlays/xv2Filter2DDilate.bit does not exist.
` 

How might I be able to get the missing file?

**Edit:**
I just noticed that this is only available for v2.3.. Is there any link to previous versions or expected timeline of when this will be upgraded?

Thank you for any help!

**Comment by jamesthesken** [comment]
Found the previous releases in case anyone needs to find them: https://github.com/Xilinx/PYNQ/releases 

I'll switch back to v2.3 until the update is done.

**Comment by jackl-xilinx** [comment]
Hi James,

The current release is limited to Pynq-Z1 and Ultra96. The notebooks and bitstreams for pynq v2.3 do not currently support ZCU104 but we are looking to release a ZCU104-supported update in the next week or so.

jack

**Comment by jamesthesken** [comment]
Thanks Jack,

Looking forward to the update, it'd be a life-saver.

**Comment by jamesthesken** [comment]
I notice in the [Boards](https://github.com/Xilinx/PYNQ-ComputerVision/tree/master/boards) directory, there is a ZCU104. Was this originally intended to be supported?

**Comment by jackl-xilinx** [comment]
Yes, it was a place holder for when ZCU104 support was added. The supported boards are listed under the top level README.md which describes which boards and pynq version this repo currently supports. If you check under the 'overlays' subfolder, you will find it empty because no bitstream/ overlay was built for the ZCU104 board yet.

**Comment by jamesthesken** [comment]
Hi @jackl-xilinx just wanted to follow up with you. Is the estimate still okay for release soon?

Thank you.

**Comment by jackl-xilinx** [comment]
Hi James,

We are working to verify the pynq enabled zcu104 platform and build the overlays for it at the moment and hope to have something within the next few days. We'll provide an update by the end of this week if it's taking longer than expected. 

jack

**Comment by jackl-xilinx** [comment]
Hi James,

We've just pushed the update to add overlays for the ZCU104 board. This is still targeting pynq v2.3 using the 2018.2 Xilinx tools as we have not yet migrated and verified the overlays for pynq v2.4. The filter2D, dilate and optical flow designs should work but we ran into an issue verifying the stereo block matching overlay which we still need to resolve. Please give it a try unless you need the stereo BM overlay, in which case it will take a bit longer to update. Thanks.

jack

**Comment by jamesthesken** [comment]
Jack,

Thank you for quickly releasing the overlays, the notebooks are very well put together. Thank you especially for the plot cells! 

I didn't run the stereo BM overlay, however I tried the tracking example notebook and on the HW acceleration cell the kernel keeps dying. Any idea why that might be?

Thank you for your great support.

**Comment by jamesthesken** [comment]
One more question, is it possible to import multiple overlays?

eg. importing the optical flow in addition to dilation

**Comment by jamesthesken** [comment]
Just pinging this issue.

**Comment by denolf** [comment]
Hi James,

You are correct, HDMI support is only available for the PYNQ-Z1. For the other platforms (Ultra96, ZCU104, etc) we wanted to retain as much as possible PL resource for the CV blocks.

It is currently not possible to import multiple overlays at runtime. Using the CMake based sds++ cross compilation, you can build your own overlay containing both CV blocks you mention (add and dilate). Please have a look at the README: https://github.com/Xilinx/PYNQ-ComputerVision/tree/master/overlays

We are still working on a good fix tor the issue with the example notebook. 

Regards

Kristof

**Comment by jamesthesken** [comment]
Hi @denolf thank you for your response.

Is it a plan to make importing multiple overlays possible in future versions? Being a software engineer not specialized in hardware, this is something my team and I are hoping to see. 

If there is a good explanation for that it would be good to see in the documentation, I am curious. 

Thank you,
James

**Comment by shlean** [comment]
hi，I also met the same problem both on PYNQ-Z1 and ZCU104. Both of the firewares are V2.3
I found that the installing directory (pynq_cv-2.3-py3.6.egg) is not available.
root@pynq:/usr/local/lib/python3.6/dist-packages# ll
drwxr-sr-x  6 xilinx xilinx    4096 Sep 11 02:17 pynq/
drwxr-sr-x  2 root   staff     4096 Sep 11 02:46 pynq-2.3.egg-info/
-rw-r--r--  1 root   staff  2371372 Sep 11 02:25 pynq_cv-2.3-py3.6.egg
drwxr-sr-x  4 root   staff     4096 Sep 10 20:16 rise/
drwxr-sr-x  2 root   staff     4096 Sep 10 20:16 rise-5.2.0.dist-info/
drwxr-sr-x  4 root   staff     4096 Sep 10 20:11 sphinx_rtd_theme/
drwxr-sr-x  2 root   staff     4096 Sep 10 20:11 sphinx_rtd_theme-0.4.1.dist-info/
drwxr-sr-x  5 root   staff     4096 Sep 10 20:19 werkzeug/
drwxr-sr-x  2 root   staff     4096 Sep 10 20:19 Werkzeug-0.14.1.dist-info/

I installed the packages as follow：
root@pynq:/home/xilinx/jupyter_notebooks/PYNQ-ComputerVision# python3.6 setup.py install
running install
running bdist_egg
running egg_info
writing pynq_cv.egg-info/PKG-INFO
writing dependency_links to pynq_cv.egg-info/dependency_links.txt
writing requirements to pynq_cv.egg-info/requires.txt
writing top-level names to pynq_cv.egg-info/top_level.txt
reading manifest file 'pynq_cv.egg-info/SOURCES.txt'
writing manifest file 'pynq_cv.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-armv7l/egg
running install_lib
running build_py
creating build/bdist.linux-armv7l/egg
creating build/bdist.linux-armv7l/egg/pynq_cv
copying build/lib/pynq_cv/__init__.py -> build/bdist.linux-armv7l/egg/pynq_cv
creating build/bdist.linux-armv7l/egg/pynq_cv/overlays
copying build/lib/pynq_cv/overlays/xv2Filter2DDilate.bit -> build/bdist.linux-armv7l/egg/pynq_cv/overlays
copying build/lib/pynq_cv/overlays/__init__.py -> build/bdist.linux-armv7l/egg/pynq_cv/overlays
copying build/lib/pynq_cv/overlays/xv2Filter2DRemap.bit -> build/bdist.linux-armv7l/egg/pynq_cv/overlays
copying build/lib/pynq_cv/overlays/xv2Filter2DDilate.so -> build/bdist.linux-armv7l/egg/pynq_cv/overlays
copying build/lib/pynq_cv/overlays/xv2Filter2DRemap.hwh -> build/bdist.linux-armv7l/egg/pynq_cv/overlays
copying build/lib/pynq_cv/overlays/xv2Filter2DRemap.so -> build/bdist.linux-armv7l/egg/pynq_cv/overlays
copying build/lib/pynq_cv/overlays/xv2Filter2DDilate.hwh -> build/bdist.linux-armv7l/egg/pynq_cv/overlays
byte-compiling build/bdist.linux-armv7l/egg/pynq_cv/__init__.py to __init__.cpython-36.pyc
byte-compiling build/bdist.linux-armv7l/egg/pynq_cv/overlays/__init__.py to __init__.cpython-36.pyc
creating build/bdist.linux-armv7l/egg/EGG-INFO
copying pynq_cv.egg-info/PKG-INFO -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pynq_cv.egg-info/SOURCES.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pynq_cv.egg-info/dependency_links.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pynq_cv.egg-info/requires.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
copying pynq_cv.egg-info/top_level.txt -> build/bdist.linux-armv7l/egg/EGG-INFO
writing build/bdist.linux-armv7l/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
creating 'dist/pynq_cv-2.3-py3.6.egg' and adding 'build/bdist.linux-armv7l/egg' to it
removing 'build/bdist.linux-armv7l/egg' (and everything under it)
Processing pynq_cv-2.3-py3.6.egg
Removing /usr/local/lib/python3.6/dist-packages/pynq_cv-2.3-py3.6.egg
Copying pynq_cv-2.3-py3.6.egg to /usr/local/lib/python3.6/dist-packages
pynq-cv 2.3 is already the active version in easy-install.pth

Installed /usr/local/lib/python3.6/dist-packages/pynq_cv-2.3-py3.6.egg
Processing dependencies for pynq-cv==2.3
Searching for pynq==2.3
Best match: pynq 2.3
Adding pynq 2.3 to easy-install.pth file
Installing start_pl_server.py script to /usr/local/bin
Installing stop_pl_server.py script to /usr/local/bin

Using /usr/local/lib/python3.6/dist-packages
Finished processing dependencies for pynq-cv==2.3

It seemed that the packages were installed successfully. So what is the problem? Thank you for any help!

**Comment by shlean** [comment]
it seemed that the packages must be installed through sudo pip3 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git
now it work!

I have a quetion is why the packages can not be installed through the steps as following:

git clone sudo -H pip3 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git
cd PYNQ-ComputerVision
python3.6 setup.py install

**Comment by jamesthesken** [comment]
The installation instructions are in the readme @shlean
