### ISSUE TITLE
issues about filter2d

### ISSUE THREAD

**Issue by yunqu** [Xilinx/PYNQ-ComputerVision#2]
For some reason the camera resolution is locked at:
My mode: VideoMode: width=1280 height=720 bpp=8

Then running this will give the following error:
![image](https://user-images.githubusercontent.com/14114006/37493464-3bb81078-2862-11e8-88fd-11c58b656a7a.png)

**Comment by Yidagithub1103** [comment]
Hi!
I meet an issues with the install.
I followed the step in the Quick Start,but there is an error:
`ack (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-4x5m6nm0/setup.py", line 66, in <module>
        install_packages()
      File "/tmp/pip-req-build-4x5m6nm0/setup.py", line 50, in install_packages
        subprocess.check_call(['pip3.6', 'install'])
      File "/opt/python3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pip3.6', 'install']' returned non-zero exit status 1.
`
Can you help me?THX!

**Comment by sirwalterrrich** [comment]
Hello,
I'm getting the following installation error. I'm using PYNQ 2.1

```
xilinx@pynq:~$ sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git
[sudo] password for xilinx:
Collecting git+https://github.com/Xilinx/PYNQ-ComputerVision.git
  Cloning https://github.com/Xilinx/PYNQ-ComputerVision.git to /tmp/pip-req-build-l5ai_fn1
Installing collected packages: pynq-computervision
  Running setup.py install for pynq-computervision ... error
    Complete output from command /opt/python3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-l5ai_fn1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-of5yslgz/install-record.txt --single-version-externally-managed --compile:
    Reading package lists...
    Building dependency tree...
    Reading state information...
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
    ERROR: You must give at least one requirement to install (see "pip help install")
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-l5ai_fn1/setup.py", line 66, in <module>
        install_packages()
      File "/tmp/pip-req-build-l5ai_fn1/setup.py", line 50, in install_packages
        subprocess.check_call(['pip3.6', 'install'])
      File "/opt/python3.6/lib/python3.6/subprocess.py", line 291, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['pip3.6', 'install']' returned non-zero exit status 1.

    ----------------------------------------
Command "/opt/python3.6/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-l5ai_fn1/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-of5yslgz/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-l5ai_fn1/
```
Can someone help me? Thanks

**Comment by yunqu** [comment]
@Yidagithub1103 @sirwalterrrich  if you guys have problems with the pip install, please try to use

```shell
sudo pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git
```

Also, make sure you have proper internet connection. If you are behind a proxy, try to export http_proxy and https_proxy.

**Comment by yunqu** [comment]
Closing since we will support image v2.3 shortly
