### ISSUE TITLE
Compiler Bug

### ISSUE THREAD

**Issue by ctz16** [Xilinx/PYNQ-ComputerVision#21]
Hello all,

Excited to see that all of you work to make it possible for SDx to cooperate with cmake! It makes many things possible.

I met some errors while first utilizing the toolchain file. Could you please help me fix it?

OS: Windows 10
cmake Generator: mingw makefile
cmake options: as the following image
![image](https://user-images.githubusercontent.com/31756161/59962216-f4c5d080-9514-11e9-84d5-b141cb66c7b9.png)

```
Platform system configuration option -sds-sys-config was not specified, searching for a configuration that uses the specified OS linux
Using system configuration -sds-sys-config a53_linux
ERROR: [SdsCompiler 83-5184] Can't find aarch64-linux-gnu-g++ in PATH - please run the settings64 script in the installation, or use a terminal with the environment set up to run SDSoC
ERROR: [SdsCompiler 83-5004] Build failed
```

At the first time of cmake configure, it failed to find the aarch64-linux-gnu-gcc and aarch64-linux-gnu-g++ compiler so I set the system path manually, which is the path to my SDx gnu compilers.

![image](https://user-images.githubusercontent.com/31756161/59962248-525a1d00-9515-11e9-8549-b0e61e3d92d7.png)

However, the compiler failed to compile anything. It just failed at the compiler test part.

```

CMake Error at C:/Program Files/CMake/share/cmake-3.14/Modules/CMakeTestCCompiler.cmake:60 (message):
  The C compiler

    "D:/Xilinx/SDx/2019.1/bin/sdscc.bat"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/CMakeTmp
    
    Run Build Command(s):C:/MinGW/bin/mingw32-make.exe cmTC_2338c/fast 
    C:/MinGW/bin/mingw32-make.exe -f CMakeFiles\cmTC_2338c.dir\build.make CMakeFiles/cmTC_2338c.dir/build

    mingw32-make.exe[1]: Entering directory 'E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/CMakeTmp'

    Building C object CMakeFiles/cmTC_2338c.dir/testCCompiler.o

    D:\Xilinx\SDx\2019.1\bin\sdscc.bat  -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7 -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7\aarch64-linux-gnu -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7\backward -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\aarch64-linux-gnu -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\glib-2.0 -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\lib\glib-2.0\include -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1 -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1\aarch64-linux-gnu -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1\backward -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\lib\gcc\aarch64-linux-gnu\6.2.1\include -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\lib\gcc\aarch64-linux-gnu\6.2.1\include-fixed -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include  -sds-pf zcu102 -dmclkid 0  -mno-boot-files -mstrict-align -hls-target 1    -o CMakeFiles\cmTC_2338c.dir\testCCompiler.o   -c E:\workspace\FPGA\openMVG_debug\build\CMakeFiles\CMakeTmp\testCCompiler.c

           XILINX_VIVADO: "D:/Xilinx/Vivado/2019.1"

       XILINX_VIVADO_HLS: "D:/Xilinx/Vivado/2019.1"

              XILINX_SDK: "D:/Xilinx/SDK/2019.1"

              XILINX_SDX: "D:/Xilinx/SDx/2019.1"

    XILINXD_LICENSE_FILE: ""

         **** ENVIRONMENT DEBUG INFO ****

                  XILINX: ""

              XILINX_SDK: "D:/Xilinx/SDK/2019.1"

             XILINX_PATH: ""

             RDI_BINROOT: "D:/Xilinx/SDx/2019.1/bin"

             RDI_APPROOT: "D:/Xilinx/SDx/2019.1"

             HDI_APPROOT: "D:/Xilinx/SDx/2019.1"

            RDI_BASEROOT: "D:/Xilinx/SDx"

             RDI_DATADIR: "D:/Xilinx/SDx/2019.1/data"

              RDI_LIBDIR: "D:/Xilinx/SDx/2019.1/lib/win64.o"

              RDI_BINDIR: "D:/Xilinx/SDx/2019.1/bin"

    XILINXD_LICENSE_FILE: ""

            RDI_JAVAROOT: "D:/Xilinx/SDx/2019.1/tps/win64/jre9.0.4"

                    PATH: "D:/Xilinx/SDx/2019.1/bin;D:/Xilinx/SDx/2019.1/lib/win64.o;D:/Xilinx/SDx/2019.1/tps/win64/jre9.0.4/bin/server;D:/Xilinx/SDx/2019.1/tps/win64/jre9.0.4/bin;D:/Xilinx/SDK/2019.1/bin;D:/Xilinx/SDx/2019.1\tps\win64\libxslt\bin;D:/Xilinx/SDK/2019.1\gnuwin\bin;D:/Xilinx/SDK/2019.1\gnu\arm\nt\bin;D:/Xilinx/Vivado/2019.1\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;C:\Program Files\Docker\Docker\Resources\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Administrator\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;D:\Program Files (x86)\QTSystem\;C:\Program Files (x86)\Wolfram Research\WolframScript\;D:\Program Files\Git\cmd;D:\Program Files\Microsoft VS Code\bin;D:\Program Files\Matlab\runtime\win64;D:\Program Files\Matlab\bin;D:\Program Files\mysql\mysql-5.7.24-winx64\bin;;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\CMake\bin;C:\Program Files\PuTTY\;C:\Users\Administrator\AppData\Local\Programs\Python\Python36\Scripts\;C:\Users\Administrator\AppData\Local\Programs\Python\Python36\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;D:\Program Files\tex\bin\win32;D:\Program Files\Anaconda3\Scripts;C:\Users\Administrator\AppData\Local\GitHubDesktop\bin;D:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\bin;D:/Xilinx/SDx/2019.1\tps\mingw\6.2.0\win64.o\nt\bin;D:/Xilinx/SDx/2019.1\tps\mingw\6.2.0\win64.o\nt\libexec\gcc\x86_64-w64-mingw32\6.2.0"

    Platform system configuration option -sds-sys-config was not specified, searching for a configuration that uses the specified OS linux

    Using system configuration -sds-sys-config a53_linux

    Analyzing source for RTL template usage

    Create data motion intermediate representation

    

    E:\workspace\FPGA\openMVG_debug\build\CMakeFiles\CMakeTmp>D:\Xilinx\SDx\2019.1\llvm-clang\win64\llvm\bin\clang.exe -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7 -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7\aarch64-linux-gnu -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7\backward -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\aarch64-linux-gnu -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\glib-2.0 -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\lib\glib-2.0\include -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1 -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1\aarch64-linux-gnu -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1\backward -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\lib\gcc\aarch64-linux-gnu\6.2.1\include -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\lib\gcc\aarch64-linux-gnu\6.2.1\include-fixed -ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include -mstrict-align -D __SDSCC__ -target aarch64-linux-gnu -mcpu=cortex-a53 -O0 -g -I D:/Xilinx/SDx/2019.1/target/aarch64-linux/include -D HLS_NO_XIL_FPO_LIB -I D:/Xilinx/Vivado/2019.1/include -ID:/Xilinx/SDK/2019.1/gnu/aarch64/nt/aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0/include -ID:/Xilinx/SDK/2019.1/gnu/aarch64/nt/aarch64-linux/lib/gcc/aarch64-linux-gnu/8.2.0/include-fixed -ID:/Xilinx/SDK/2019.1/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu/include -ID:/Xilinx/SDK/2019.1/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu/libc/usr/include -emit-llvm -S E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/CMakeTmp/testCCompiler.c -o E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/CMakeTmp/_sds/.llvm/CMakeFiles/cmTC_2338c.dir/testCCompiler.s 

    

    E:\workspace\FPGA\openMVG_debug\build\CMakeFiles\CMakeTmp>exit /b 0 

    Compiling E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/CMakeTmp/testCCompiler.c

    Assembler messages:

    Fatal error: can't create CMakeFilescmTC_2338c.dir	estCCompiler.o: Invalid argument

    ERROR: [SdsCompiler 83-5019] Exiting sdscc : Error when calling 'aarch64-linux-gnu-gcc -c {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7\aarch64-linux-gnu} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\c++\7\backward} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\aarch64-linux-gnu} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\include\glib-2.0} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\usr\lib\glib-2.0\include} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1\aarch64-linux-gnu} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include\c++\6.2.1\backward} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\lib\gcc\aarch64-linux-gnu\6.2.1\include} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\lib\gcc\aarch64-linux-gnu\6.2.1\include-fixed} {-ID:\Xilinx\SDK\2019.1\gnu\aarch64\nt\aarch64-linux\aarch64-linux-gnu\include} -mstrict-align -D __SDSCC__        -I D:/Xilinx/SDx/2019.1/target/aarch64-linux/include  -D HLS_NO_XIL_FPO_LIB  -I D:/Xilinx/Vivado/2019.1/include E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/CMakeTmp/testCCompiler.c -o CMakeFiles\cmTC_2338c.dir\testCCompiler.o'

    sdscc log file saved as E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/CMakeTmp/_sds/reports/sds_testCCompiler.log

    ERROR: [SdsCompiler 83-5004] Build failed

    

    CMakeFiles\cmTC_2338c.dir\build.make:64: recipe for target 'CMakeFiles/cmTC_2338c.dir/testCCompiler.o' failed

    mingw32-make.exe[1]: *** [CMakeFiles/cmTC_2338c.dir/testCCompiler.o] Error 1

    mingw32-make.exe[1]: Leaving directory 'E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/CMakeTmp'

    Makefile:120: recipe for target 'cmTC_2338c/fast' failed

    mingw32-make.exe: *** [cmTC_2338c/fast] Error 2

    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:10 (project)

```
The compile command is the key command to cause failure.
```
ERROR: [SdsCompiler 83-5019] Exiting sds++ : Error when calling 'aarch64-linux-gnu-g++     E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/3.14.4/CompilerIdCXX/CMakeCXXCompilerId.cpp E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/3.14.4/CompilerIdCXX/_sds/swstubs/portinfo.o -mstrict-align    -LE:/workspace/FPGA/openMVG_debug/build/CMakeFiles/3.14.4/CompilerIdCXX/_sds/swstubs -Wl,--start-group  -Wl,--end-group -Wl,--start-group    -lpthread -LD:/Xilinx/SDx/2019.1/target/aarch64-linux/lib -lsds_lib -lxlnk_stub  -Wl,--end-group -o E:/workspace/FPGA/openMVG_debug/build/CMakeFiles/3.14.4/CompilerIdCXX/_sds/swstubs '
```

I am confused at where is wrong so I invoked the same compile command in my powershell and found the following errors.

![image](https://user-images.githubusercontent.com/31756161/59962143-1d00ff80-9514-11e9-87cb-3c03876c624b.png)

I can not understand why it failed. Seems like that the compiler can not recognize -Wl,--start-group option. Any suggestion on the issue?

Sincerely thanks in advance.

**Comment by denolf** [comment]
Hi,

Thanks for your enthusiasm on our CMake SDx build flow.

On Windows (10), we run cmake from the command line in a "SDx Terminal 2018.2" (installed under the Xilinx Design Tools) and specify to generate "Unix Makefiles" 

For example: 

cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=..\..\..\..\frameworks\cmakeModules\cmakeModulesXilinx\toolchain_sds.cmake -DSDxPlatform=X:\projects\image_processing\platforms\Ultra96\ultra_v2.3\2018.2\ultra -DSDxClockID=1 -DusePL=ON -DnoBitstream=OFF -DnoSDCardImage=ON -DSDxArch=arm64

Regards

Kristof

**Comment by ctz16** [comment]
Thank you, Kristof
I've tried your suggestions and met the following problems,

C:\Users\chang\fpga\PYNQ-ComputerVision\overlays\myFirstOverlay\build>cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../../../frameworks/cmakeModules/toolchain_sdx2018.2.cmake -DSDxPlatform=../../../../ultra -DSDxClockID=1 -DusePL=ON -DnoBitstream=OFF -DnoSDCardImage=ON -DSDxArch=arm64
-- SDx platform: ../../../../ultra , clock ID: 1, aarch: arm64 bit
-- Selected Options: usePL=ON, noBitstream: OFF, noSDCardImage=ON
-- CMAKE C FLAGS -sds-pf ../../../../ultra -dmclkid 1  -mno-boot-files -mstrict-align -hls-target 1
-- SDx sysroot: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu/libc
-- CMAKE_FIND_ROOT_PATH: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu
-- CMAKE_AR: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu/bin/ar
-- OpenCV ARCH:
-- OpenCV RUNTIME:
-- OpenCV STATIC: ON
CMake Warning at C:/Users/chang/Anaconda3/Library/OpenCVConfig.cmake:140 (message):
  Found OpenCV Windows Pack but it has no binaries compatible with your
  configuration.

  You should manually point CMake variable OpenCV_DIR to your build of OpenCV
  library.
Call Stack (most recent call first):
  C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxTargets.cmake:59 (find_package)
  C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxXfOpenCV.cmake:843 (requireOpenCVAndVivadoHLS)
  C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxXfOpenCV.cmake:933 (createXfOpenCVOverlayWithPythonBindings)
  CMakeLists.txt:56 (createOverlayWithPythonBindings)


CMake Error at C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxTargets.cmake:59 (find_package):
  Found package configuration file:

    C:/Users/chang/Anaconda3/Library/OpenCVConfig.cmake

  but it set OpenCV_FOUND to FALSE so package "OpenCV" is considered to be
  NOT FOUND.
Call Stack (most recent call first):
  C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxXfOpenCV.cmake:843 (requireOpenCVAndVivadoHLS)
  C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxXfOpenCV.cmake:933 (createXfOpenCVOverlayWithPythonBindings)
  CMakeLists.txt:56 (createOverlayWithPythonBindings)


-- Configuring incomplete, errors occurred!

It seemed that cmake didn't find my opencv build path. So I tried:

-DOpenCV_DIR=C:\Users\chang\Anaconda3\Library\lib

and then another error:

C:\Users\chang\fpga\PYNQ-ComputerVision\overlays\myFirstOverlay\build>cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE=../../../frameworks/cmakeModules/toolchain_sdx2018.2.cmake -DSDxPlatform=../../../../ultra -DSDxClockID=1 -DusePL=ON -DnoBitstream=OFF -DnoSDCardImage=ON -DSDxArch=arm64 -DOpenCV_DIR=C:\Users\chang\Anaconda3\Library\lib
-- SDx platform: ../../../../ultra , clock ID: 1, aarch: arm64 bit
-- Selected Options: usePL=ON, noBitstream: OFF, noSDCardImage=ON
-- CMAKE C FLAGS -sds-pf ../../../../ultra -dmclkid 1  -mno-boot-files -mstrict-align -hls-target 1
-- SDx sysroot: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu/libc
-- CMAKE_FIND_ROOT_PATH: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu
-- CMAKE_AR: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu/bin/ar
-- SDx platform: ../../../../ultra , clock ID: 1, aarch: arm64 bit
-- Selected Options: usePL=ON, noBitstream: OFF, noSDCardImage=ON
-- CMAKE C FLAGS -sds-pf ../../../../ultra -dmclkid 1  -mno-boot-files -mstrict-align -hls-target 1
-- SDx sysroot: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu/libc
-- CMAKE_FIND_ROOT_PATH: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu
-- CMAKE_AR: C:/Xilinx/SDK/2018.2/gnu/aarch64/nt/aarch64-linux/aarch64-linux-gnu/bin/ar
CMake Error at C:/Users/chang/Anaconda3/Library/lib/OpenCVModules.cmake:368 (message):
  The imported target "opencv_core" references the file

     "C:/Users/chang/x64/vc14/lib/opencv_core341.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "C:/Users/chang/Anaconda3/Library/lib/OpenCVModules.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  C:/Users/chang/Anaconda3/Library/lib/OpenCVConfig.cmake:112 (include)
  C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxTargets.cmake:59 (find_package)
  C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxXfOpenCV.cmake:843 (requireOpenCVAndVivadoHLS)
  C:/Users/chang/fpga/PYNQ-ComputerVision/frameworks/cmakeModules/rulesForSDxXfOpenCV.cmake:933 (createXfOpenCVOverlayWithPythonBindings)
  CMakeLists.txt:56 (createOverlayWithPythonBindings)


-- Configuring incomplete, errors occurred!

I can not understand why cmake should find my opencv installed in anaconda, because it should not depend on anaconda. I thought it was supposed to find my xfopencv path, but there is no binary libraries in the xfopencv, only cpp and hpp. Do you have any suggestions?

**Comment by denolf** [comment]
Hi,

Can you try again but specifying an absolute path for your SDxPlatform?

Regards

Kristof

**Comment by denolf** [comment]
Closing, please open a new issue if the absolute path this not resolve this.
