### ISSUE TITLE
Error when trying to make an overlay with xf::fast

### ISSUE THREAD

**Issue by amirkiperwas** [Xilinx/PYNQ-ComputerVision#22]
/work/XFOPENCV/PYNQ-ComputerVision/overlays/xv2FastOverlay/build/inc/xilinx_pyopencv_modules_in_overlay.h:6:23: error: use of undeclared identifier 'pyopencv_cv_LUT'
        {"fast",(PyCFunction)pyopencv_cv_LUT, METH_VARARGS | METH_KEYWORDS, "fast(src, lut[, dst]) -> dst"},
                             ^
ERROR: [SdsCompiler 83-5005] clang exited with non-zero code processing /work/XFOPENCV/PYNQ-ComputerVision/overlays/xv2FastOverlay/build/src/cv_xilinx.cpp

[sds_cv_xilinx.log](https://github.com/Xilinx/PYNQ-ComputerVision/files/3351359/sds_cv_xilinx.log)
[CMakeLists.txt](https://github.com/Xilinx/PYNQ-ComputerVision/files/3351362/CMakeLists.txt)

**Comment by denolf** [comment]
Thanks for pointing this out. There is indeed a problem with the xF::fast Python binding. We are working on a fix.

Regards

Kristof

**Comment by jackl-xilinx** [comment]
Please try the fix in our latest 2018.3 release.
