### ISSUE TITLE
Error in using created overlay on ZedBoard

### ISSUE THREAD

**Issue by shravan-red** [Xilinx/PYNQ-ComputerVision#23]
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-0da698e01a42> in <module>()
      1 OVERLAY_PATH = 'halfsqueezenet_overlay.bit'
----> 2 overlay = Overlay(OVERLAY_PATH)
      3 dma = overlay.axi_dma_0
      4 WEIGHTS_FILE_NAME = 'halfsqueezenet_weights_file.txt'
      5 

/usr/local/lib/python3.6/dist-packages/pynq/overlay.py in __init__(self, bitfile_name, download, partial, ignore_version)
    311         self._ip_map = _IPMap(description)
    312         if download:
--> 313             self.download()
    314 
    315         self.__doc__ = _build_docstring(self._ip_map._description,

/usr/local/lib/python3.6/dist-packages/pynq/overlay.py in download(self)
    350                 Clocks.set_pl_clk(i)
    351 
--> 352         super().download()
    353         PL.reset(self.parser)
    354 

/usr/local/lib/python3.6/dist-packages/pynq/pl.py in download(self)
   1603 
   1604         """
-> 1605         self._download()
   1606         if not self.partial:
   1607             self._update_pl()

/usr/local/lib/python3.6/dist-packages/pynq/pl.py in _download(self)
   1648         """
   1649         if not os.path.exists(self.BS_FPGA_MAN):
-> 1650             raise RuntimeError("Could not find programmable device")
   1651 
   1652         bin_file = os.path.basename(self.bitfile_name).replace('.bit', '.bin')

RuntimeError: Could not find programmable device

Device : ZedBoard with PynqLinux Ubuntu 18.04

**Comment by denolf** [comment]
Did you try to load one of the overlays available on this repo on your ZedBoard. If yes, that will not work since the ZedBoard is not supported.

Or did you create your own overlay specifically for a ZedBoard?

**Comment by shravan-red** [comment]
I created a custom overlay using the code in the link https://pynq.readthedocs.io/en/v2.3/overlay_design_methodology/overlay_tutorial.html
PYNQ image has been  loaded  to Zedboard's SD card, and the boot was successful.

**Comment by yunqu** [comment]
The error indicates that you don't have this file in your rootfs: `/sys/class/fpga_manager/fpga0/firmware`. This is required as part of the FPGA manager.

What version of the image are you using and what version of the pynq package are you using? They have to match so if you upgrade your pynq package on top of an older version of the PYNQ image, it will not work.

**Comment by shravan-red** [comment]
The directory /sys/class/fpga_manager is missing altogether. I used Pynq Z1 v2.3 image from https://github.com/Xilinx/PYNQ/releases

**Comment by shravan-red** [comment]
I downloaded and loaded onto my Zedboard the PYNQ Z1 v2.4 image from the same aforementioned link and there isn't a folder named fpga_manager inside sys/class

> The error indicates that you don't have this file in your rootfs: `/sys/class/fpga_manager/fpga0/firmware`. This is required as part of the FPGA manager.
> 
> What version of the image are you using and what version of the pynq package are you using? They have to match so if you upgrade your pynq package on top of an older version of the PYNQ image, it will not work.

**Comment by yunqu** [comment]
It looks that something is wrong with your Zedboard image. I don't think you can boot pynqz1 image on zedboard.

**Comment by shravan-red** [comment]
> It looks that something is wrong with your Zedboard image. I don't think you can boot pynqz1 image on zedboard.

Could you suggest an alternative image that I can burn to zedboard's SD card ?

**Comment by denolf** [comment]
closing due to follow up in https://github.com/Xilinx/PYNQ-ComputerVision/issues/24
