### ISSUE TITLE
Eth0 not found : Zedboard Pynq V2.3

### ISSUE THREAD

**Issue by shravan-red** [Xilinx/PYNQ-ComputerVision#24]
Because of my previous problem with overlay import where I couldn't download any bitstream file to my Zedboard while using the Pynq_Z1_v2.3 image on my SD card, I built a customized SD card pynq_v2.3 image for my Zedboard using PetaLinux 2018.2 with bionic.arm.2.3.img as base and avnet-digilent-zedboard-2018.2.bsp (both downloaded from Xilinx). The Zedboard booted from the SD card but I'm unable to connect to the local network through ethernet; on running ifconfig command only loopback address (127.0.0.1) is returned. There is no eth0. I can't use Jupyter Notebooks. Please suggest a solution

**Comment by yunqu** [comment]
looks like a device tree problem. You probably need some similar u-boot patches as pynqz1 or pynqz2.

You also need to add eth0 package.

Please post your further questions on https://discuss.pynq.io/

**Comment by denolf** [comment]
closing after comments from yunqu.
