### ISSUE TITLE
FAILED   pip3 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git

### ISSUE THREAD

**Issue by fengr0905** [Xilinx/PYNQ-ComputerVision#27]
ERROR MESSAGE:

Collecting git+https://github.com/Xilinx/PYNQ-ComputerVision.git
  Cloning https://github.com/Xilinx/PYNQ-ComputerVision.git to c:\users\cf\appdata\local\temp\pip-req-build-7rmbdw7e
  Running command git clone -q https://github.com/Xilinx/PYNQ-ComputerVision.git 'C:\Users\CF\AppData\Local\Temp\pip-req-build-7rmbdw7e'
  Running command git submodule update --init --recursive -q
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\CF\\AppData\\Local\\Temp\\pip-req-build-7rmbdw7e\\setup.py'"'"'; __file__='"'"'C:\\Users\\CF\\AppData\\Local\\Temp\\pip-req-build-7rmbdw7e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\CF\AppData\Local\Temp\pip-req-build-7rmbdw7e\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\CF\AppData\Local\Temp\pip-req-build-7rmbdw7e\setup.py", line 44, in <module>
        board = os.environ['BOARD']
      File "d:\python\lib\os.py", line 678, in __getitem__
        raise KeyError(key) from None
    KeyError: 'BOARD'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

HOW TO SOLVE THIS?

**Comment by jackl-xilinx** [comment]
Hi fengr0905. I don't see the error that you're reporting on our setup (both Ultra96 and Pynq-Z1). Can you clarify which board you're running this on? It looks kind of like you're running this on an x86 machine as opposed to the ubuntu images that we provided. Can you also confirm that you're running this on a v2.4 image and that you're running pip3 install with the sudo command.

**Comment by nhphuong91** [comment]
I have different error
`Traceback (most recent call last):`
`  File "/home/xilinx/.local/bin/pip3", line 7, in <module>`
 `   from pip._internal.main import main`
`ModuleNotFoundError: No module named 'pip._internal'`

I use ultra96v2_v2.4.img for my ultra96 v2 board

Update: Never mind! After reinstall pip, it worked:
`curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`
`python3 get-pip.py --force-reinstall`

**Comment by jackl-xilinx** [comment]
Closed due to no further confirmation of issue.
