### ISSUE TITLE
Unable to Create Custom Overlay

### ISSUE THREAD

**Issue by venkat255** [Xilinx/PYNQ-ComputerVision#5]
I'm trying to create a custom overlay, I've followed the steps mentioned in the readme, on the step,

`make xv2MyFirstOverlay`

I'm getting error.

     CMake Error at /home/kvikrama/gitHub/PYNQ- 
     ComputerVision/frameworks/cmakeModules/rulesForSDxTargets.cmake:59 (find_package):
     By not providing "FindOpenCV.cmake" in CMAKE_MODULE_PATH this project has
     asked CMake to find a package configuration file provided by "OpenCV", but
    
    CMake did not find one.

    Could not find a package configuration file provided by "OpenCV" with any
    of the following names:

    OpenCVConfig.cmake
    opencv-config.cmake

     Add the installation prefix of "OpenCV" to CMAKE_PREFIX_PATH or set
     "OpenCV_DIR" to a directory containing one of the above files.  If "OpenCV"
     provides a separate development package or SDK, be sure it has been
     installed. 

Do we need Opencv libraries to compile this?

**Comment by denolf** [comment]
Hi Venkat,

The OpenCV libraries are indeed needed, but they are included in the sysroot. Can you provide us with your CMake command line and the earlier output of CMake?

Thanks.

**Comment by jackl-xilinx** [comment]
Closing issue. Please reopen if you've tried the suggestion above and can provide more information on your issue. Thanks.
