### ISSUE TITLE
pynq-z2 problem

### ISSUE THREAD

**Issue by bardeenzyh** [Xilinx/PYNQ-ComputerVision#7]
my board: pynq-z2
image version: PYNQ-Z2 v2.3 PYNQ image

my operation:
step1: root@pynq:/home/xilinx# sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git
step2: run the filter2d_and_dilate.ipynb
Then I got error: ModuleNotFoundError: No module named 'pynq_computervision'；
And I find there is no pynq_computervision on the github；

can you help me to fix this error? and why this happened？

**Comment by jackl-xilinx** [comment]
Please pip install v1.0 with the ocommand:
sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git@v1.0

**Comment by bardeenzyh** [comment]
Hi yunqu,jackl-xilinx:
Thanks for your answers!
1.the error is solved by jackl-xilinx's solution;
2.but Nfilter2d_and_dilate.ipynb only can be used on PYNQ-Z2 v2.2 PYNQ image, PYNQ-Z2 v2.3 image's 
files directory is not compatible for the computer-vision v1.0 notbook.

**Comment by jackl-xilinx** [comment]
We are in the process of adding support for Pynq-Z1 and Pynq-Z2 for the v2.3 image and will notify you when it is ready.

**Comment by jackl-xilinx** [comment]
v2.3 support has been added for Pynq-Z2 so it should work with the standard pip3 install command. Please give it a try and open a new issue if you run into problems. Thanks.
