### ISSUE TITLE
Questions on hardware rebuilding on Pynq-Z2 board 

### ISSUE THREAD

**Issue by sxw228** [Xilinx/PYNQ-ComputerVision#8]
As is shown in the README.md, the hardware rebuild is  currently only for Pynq-Z1. If i want to rebuild it  on my Z2 board, what can i do?  Can you give me some suggestions? Thanks a lot!

**Comment by sxw228** [comment]
And there's another problem.
![image](https://user-images.githubusercontent.com/43896882/46993883-5e027200-d144-11e8-853e-05f06143ab24.png)

I set the path .But get an error.What's wrong?

**Comment by jackl-xilinx** [comment]
Please pip install v1.0 with the ocommand:
sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git@v1.0

We are in the process of adding support for Pynq-Z2 and will update when it is ready.

**Comment by MCdeineMudda** [comment]
hi, i'm using the z1 board and when i try to run 
"sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git@v1.0"
i get the error: "sudo: pip3.6: command not found"

can you help me please?

**Comment by jackl-xilinx** [comment]
The Pynq-Z1 board with image v2.3 installed has pip3 instead of pip3.6. Try running the same command with pip3 and see if that works for you.

**Comment by jackl-xilinx** [comment]
v2.3 support has been added for Pynq-Z1 and Pynq-Z2 so it should work with the standard pip3 install command. Please give it a try. Rebuild for Pynq-Z2 (and even Pynq-Z1) requires some updates from our end. We'll be updating the instructions for that in the next few days. Thanks.

**Comment by jackl-xilinx** [comment]
Closing this case since the latest v2.3 support and jupyter notebook updates should solve previous issues. Please let us know if there is anything further. Thanks.
