### ISSUE TITLE
PYNQ-Z1 can't install ComputerVision with pip3

### ISSUE THREAD

**Issue by MCdeineMudda** [Xilinx/PYNQ-ComputerVision#9]
Hi, i am trying to run the ComputerVision demo on my PYNQ-Z1 with image V2.3

First i tried this command:
"sudo pip3 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git"

It installed, but i got a ModuleNotFoundError
![modulen not found](https://user-images.githubusercontent.com/43644920/47142090-6d0f2e80-d2c2-11e8-8fdb-d26742b92fed.PNG)

Than i tried to install it with this command:
"sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git@v1.0"
i got the error: "sudo: pip3.6: command not found"

Than i tried the suggestion found in the other issue to install it just with pip3:
"sudo -H pip3 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git@v1.0"
but i got following error.
![pip3error](https://user-images.githubusercontent.com/43644920/47142478-3c7bc480-d2c3-11e8-91b2-c45e39568790.PNG)

I have checked the directories and python3.6 is installed as default and the directory computer_vision is **not located** in "/opt/python3.6/lib/python3.6/sitepackages/pynq_computervision/overlays/computer_vision/xv2Filter2DRemap.bit"

Does anyone have an idea how to solve this problem?

**Comment by MCdeineMudda** [comment]
EDIT:
I updated my pip to 3.6 and was able to use
"sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git@v1.0"

The terminal showed that it was successfully installed, but in Jupyter it did not show the pynqOpenCV Folder. So i installed
"sudo -H pip3.6 install --upgrade git+https://github.com/Xilinx/PYNQ-ComputerVision.git"
and it worked.

But there was a problem with the directories. The "computer_vision"-Directory was located at "/usr/local/lib/python3.6/dist-packages/pynq_computervision".

I copied the directories into the default location and tried to run the filter2d.ipynb. The ModuleNotFoundError disappeared, but another one occured
![importerror](https://user-images.githubusercontent.com/43644920/47159154-811c5580-d2ed-11e8-9a26-cfba5ec05f0b.PNG)


Any suggestions for my problem?
Thanks in advance.

**Comment by jackl-xilinx** [comment]
The main issue is that the Pynq-Z1 release was targeted for the image before v2.3 and has not been updated for image_v2.3. If you had the older Pynq-Z1 image and pip3 installed with tag v1.0, then it would work as original described. We will update the design for image_v2.3 so it works without the tag and notify everybody when it is available (in the next day or so).

**Comment by jackl-xilinx** [comment]
v2.3 support has been added for Pynq-Z1 so it should work with the standard pip3 install command. Please give it a try and open a new issue if you run into problems. Thanks.
